### ISSUE TITLE
Data binding with library 

### ISSUE THREAD

**Issue by patelakshay13890** [LightSun/android-databinding#1]
Hey developers,  How can I use data  binding  in  my application because  I am  new to  data  binding  concept ?
I have  an  application  module  and  one  android  lib. Module  which  has  all the  entites  those  are used in app module l..
So how  can I  use  data binding  in  my  app  with  lib. Module..﻿
Which also include  dynamic inflation of view  based on parameter in some of the  entities in library module ﻿

**Comment by LightSun** [comment]
sorry, i see it late.  you mean want to use  'android-databinding ' with local build ?

**Comment by LightSun** [comment]
if you only want to use this in local build.  you must download the all refer librarys .  
this is the extra  three libs: 
compile 'com.heaven7.core.adapter:adapter:1.0'  
compile 'com.heaven7.anno:android-anno:1.0'
compile 'com.heaven7.core.util:util-v1:1.0.1'

you can just import them as a jar.
